from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver
import pyautogui
import time
from selenium.webdriver.support.ui import Select


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 511, 351))
        font = QtGui.QFont()
        font.setFamily("Arial Nova")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.clicked.connect(self.PS3)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(20, 210, 100, 75))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.clicked.connect(self.PS4)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 210, 100, 75))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 210, 100, 75))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_3.setPalette(palette)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 210, 100, 75))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 135, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_4.setPalette(palette)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 121, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 121, 41))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(120, 20, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wycena produktu"))
        self.pushButton.setText(_translate("MainWindow", "PS3"))
        self.pushButton_2.setText(_translate("MainWindow", "PS4"))
        self.pushButton_3.setText(_translate("MainWindow", "Xbox One"))
        self.pushButton_4.setText(_translate("MainWindow", "Xbox 360"))
        self.label.setText(_translate("MainWindow", "Gra:     "))
        self.label_2.setText(_translate("MainWindow", "Cena min:     "))
        self.label_3.setText(_translate("MainWindow", "Cena max:     "))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(
                self.tab), _translate(
                "MainWindow", "Gry"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(
                self.tab_2), _translate(
                "MainWindow", "Konsole"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(
                self.tab_3), _translate(
                "MainWindow", "Akcesoria"))


    def PS3(self):
        gra = self.lineEdit.text()
        cena_min = self.lineEdit_2.text()
        cena_max = self.lineEdit_3.text()
        browser = webdriver.Chrome('/Users/kamil/Downloads/chromedriver')
        browser.maximize_window()
        browser.get('https://tradewatch.pl/reports.jsf')
        browser.find_element_by_id("j_username").send_keys(
            "kamilgorzycki@gmail.com")
        browser.find_element_by_id("j_password").send_keys("Tradewatch2019")
        browser.find_element_by_xpath(
            '//button[normalize-space()="Zaloguj"]').click()
        browser.find_element_by_xpath(
            '//button[normalize-space()="Raport produktu / kategorii"]').click()
        kategoria_0 = browser.find_element_by_id("j_idt2337")
        first = Select(kategoria_0)
        first.select_by_visible_text("Gry")
        time.sleep(0.2)
        pyautogui.moveTo(1765, 442)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.move(0, 60)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1761, 467)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.move(0, 240)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1637, 576)
        pyautogui.click()
        pyautogui.write(gra)
        pyautogui.moveTo(1629, 735)
        pyautogui.click()
        pyautogui.moveTo(1610, 581)
        pyautogui.click()
        pyautogui.moveTo(1662, 806)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1684, 850)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1632, 844)
        time.sleep(0.2)
        pyautogui.click()
        time.sleep(0.2)
        pyautogui.moveTo(1722, 560)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1805, 1074)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1509, 905)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.write(cena_min)
        pyautogui.moveTo(1709, 905)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.write(cena_max)
        browser.find_element_by_xpath(
            '//button[normalize-space()="Generuj"]').click()
        time.sleep(2.5)
        pyautogui.moveTo(738, 370)
        time.sleep(0.2)
        pyautogui.click()
        time.sleep(3.5)
        pyautogui.moveTo(157, 1302)
        time.sleep(0.2)
        pyautogui.doubleClick()
        time.sleep(5)
        pyautogui.moveTo(235, 21)
        time.sleep(0.2)
        pyautogui.click()
        time.sleep(10)
        browser.quit()


    def PS4(self):
        gra = self.lineEdit.text()
        cena_min = self.lineEdit_2.text()
        cena_max = self.lineEdit_3.text()
        browser = webdriver.Chrome('/Users/kamil/Downloads/chromedriver')
        browser.maximize_window()
        browser.get('https://tradewatch.pl/reports.jsf')
        browser.find_element_by_id("j_username").send_keys(
            "kamilgorzycki@gmail.com")
        browser.find_element_by_id(
            "j_password").send_keys("******************")
        browser.find_element_by_xpath(
            '//button[normalize-space()="Zaloguj"]').click()
        browser.find_element_by_xpath(
            '//button[normalize-space()="Raport produktu / kategorii"]').click()
        kategoria_0 = browser.find_element_by_id("j_idt2337")
        first = Select(kategoria_0)
        first.select_by_visible_text("Gry")
        time.sleep(0.2)
        pyautogui.moveTo(1765, 442)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.move(0, 60)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1761, 467)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.move(0, 265)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1637, 576)
        pyautogui.click()
        pyautogui.write(gra)
        #yoyo = browser.find_element_by_xpath('//*[@id="j_idt2345"]')
        # yoyo.delete_to.send_keys(gra)
        pyautogui.moveTo(1629, 735)
        pyautogui.click()
        pyautogui.moveTo(1610, 581)
        pyautogui.click()
        pyautogui.moveTo(1662, 806)
        time.sleep(1)
        pyautogui.click()
        pyautogui.moveTo(1684, 850)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1632, 844)
        time.sleep(0.2)
        pyautogui.click()
        time.sleep(0.2)
        pyautogui.moveTo(1722, 560)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1805, 1074)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.moveTo(1509, 905)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.write(cena_min)
        pyautogui.moveTo(1709, 905)
        time.sleep(0.2)
        pyautogui.click()
        pyautogui.write(cena_max)
        browser.find_element_by_xpath(
            '//button[normalize-space()="Generuj"]').click()
        time.sleep(2.5)
        pyautogui.moveTo(738, 370)
        time.sleep(1)
        pyautogui.click()
        time.sleep(3.5)
        pyautogui.moveTo(157, 1302)
        time.sleep(1)
        pyautogui.doubleClick()
        time.sleep(5)
        pyautogui.moveTo(235, 21)
        time.sleep(1)
        pyautogui.click()
        time.sleep(10)
        browser.quit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
